### ISSUE TITLE
Keeping up-to-date with Frequency Manager plugin?

### ISSUE THREAD

**Issue by TeddJohnson** [darauble/bookmark_manager#10]
I haven't dug into the code enough to know but I do see that SDR++ has made some changes to their frequency-manager module:

https://github.com/AlexandreRouma/SDRPlusPlus/commits/master/misc_modules/frequency_manager

is there anything in these changes that would benefit this project?

I wish GIT had a native way to only fork a specific folder :)

thanks for making this!

**Comment by darauble** [comment]
The logging framework was changed, yes, otherwise it wouldn't compile :-)

**Comment by TeddJohnson** [comment]
I'm having issues compiling anyways, but that's likely because of windows 🙃
