### ISSUE TITLE
Undefinded symbols for architecture x86_64

### ISSUE THREAD

**Issue by betzburger** [darauble/bookmark_manager#3]
Well well, today I like to build the bookmark_manager with an Intel Mac. 
I can successfully build SDR++ without bookmark_manager, but as soon as I include bookmark_manager I get this error.

Any ideas what I can do to fix it?

`[ 98%] Building CXX object misc_modules/bookmark_manager/CMakeFiles/bookmark_manager.dir/src/utc.cpp.o
[100%] Linking CXX shared library bookmark_manager.dylib
Undefined symbols for architecture x86_64:
  "void fmt::v10::detail::vformat_to<char>(fmt::v10::detail::buffer<char>&, fmt::v10::basic_string_view<char>, fmt::v10::detail::vformat_args<char>::type, fmt::v10::detail::locale_ref)", referenced from:
      spdlog::details::full_formatter::format(spdlog::details::log_msg const&, tm const&, fmt::v10::basic_memory_buffer<char, 250ul, std::__1::allocator<char>>&) in main.cpp.o
      spdlog::details::c_formatter<spdlog::details::scoped_padder>::format(spdlog::details::log_msg const&, tm const&, fmt::v10::basic_memory_buffer<char, 250ul, std::__1::allocator<char>>&) in main.cpp.o
      spdlog::details::C_formatter<spdlog::details::scoped_padder>::format(spdlog::details::log_msg const&, tm const&, fmt::v10::basic_memory_buffer<char, 250ul, std::__1::allocator<char>>&) in main.cpp.o
      spdlog::details::D_formatter<spdlog::details::scoped_padder>::format(spdlog::details::log_msg const&, tm const&, fmt::v10::basic_memory_buffer<char, 250ul, std::__1::allocator<char>>&) in main.cpp.o
      spdlog::details::m_formatter<spdlog::details::scoped_padder>::format(spdlog::details::log_msg const&, tm const&, fmt::v10::basic_memory_buffer<char, 250ul, std::__1::allocator<char>>&) in main.cpp.o
      spdlog::details::d_formatter<spdlog::details::scoped_padder>::format(spdlog::details::log_msg const&, tm const&, fmt::v10::basic_memory_buffer<char, 250ul, std::__1::allocator<char>>&) in main.cpp.o
      spdlog::details::H_formatter<spdlog::details::scoped_padder>::format(spdlog::details::log_msg const&, tm const&, fmt::v10::basic_memory_buffer<char, 250ul, std::__1::allocator<char>>&) in main.cpp.o
      ...
  "fmt::v10::vformat(fmt::v10::basic_string_view<char>, fmt::v10::basic_format_args<fmt::v10::basic_format_context<fmt::v10::appender, char>>)", referenced from:
      spdlog::logger::sink_it_(spdlog::details::log_msg const&) in main.cpp.o
      void spdlog::logger::log_<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&>(spdlog::source_loc, spdlog::level::level_enum, fmt::v10::basic_string_view<char>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) in main.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [misc_modules/bookmark_manager/bookmark_manager.dylib] Error 1
make[1]: *** [misc_modules/bookmark_manager/CMakeFiles/bookmark_manager.dir/all] Error 2
make: *** [all] Error 2
`

**Comment by darauble** [comment]
Please update the source. During last half-year the logging framework has changed in SDR++. I don't recompile it often and follow the development of SDR++ actively.

**Comment by betzburger** [comment]
Problem solved! Thank you, sir!
